#!/usr/bin/env bash
# ~/opam-scripts/read-opam.sh
eval "OPAMSWITCH='coq-8.12'; export OPAMSWITCH;
OPAM_SWITCH_PREFIX='/root/.opam/coq-8.12'; export OPAM_SWITCH_PREFIX;
CAML_LD_LIBRARY_PATH='/root/.opam/coq-8.12/lib/stublibs:/root/.opam/coq-8.12/lib/ocaml/stublibs:/root/.opam/coq-8.12/lib/ocaml'; export CAML_LD_LIBRARY_PATH;
OCAML_TOPLEVEL_PATH='/root/.opam/coq-8.12/lib/toplevel'; export OCAML_TOPLEVEL_PATH;
MANPATH=':/root/.opam/coq-8.12/man'; export MANPATH;
PATH=$PATH:'/root/.opam/coq-8.12/bin:/root/.local/bin:/root/.opam/default/bin:/root/.opam/default/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin'; export PATH;"
cd ../../
source ./bin/activate
./src/scrape.py -c --prelude=./coq-projects/math-comp  mathcomp/all/all.v mathcomp/ssreflect/path.v mathcomp/ssreflect/prime.v mathcomp/ssreflect/ssreflect.v mathcomp/ssreflect/ssrfun.v mathcomp/ssreflect/ssrnotations.v mathcomp/ssreflect/all_ssreflect.v mathcomp/ssreflect/fintype.v mathcomp/ssreflect/binomial.v mathcomp/ssreflect/generic_quotient.v mathcomp/ssreflect/eqtype.v mathcomp/ssreflect/bigop.v mathcomp/ssreflect/order.v mathcomp/ssreflect/ssrbool.v mathcomp/ssreflect/div.v mathcomp/ssreflect/seq.v mathcomp/ssreflect/ssrmatching.v mathcomp/ssreflect/choice.v mathcomp/ssreflect/fingraph.v mathcomp/ssreflect/tuple.v mathcomp/ssreflect/finset.v mathcomp/ssreflect/ssrnat.v mathcomp/ssreflect/finfun.v mathcomp/ssreflect/ssrAC.v mathcomp/character/vcharacter.v mathcomp/character/classfun.v mathcomp/character/character.v mathcomp/character/all_character.v mathcomp/character/mxrepresentation.v mathcomp/character/integral_char.v mathcomp/character/mxabelem.v mathcomp/character/inertia.v mathcomp/fingroup/quotient.v mathcomp/fingroup/gproduct.v mathcomp/fingroup/automorphism.v mathcomp/fingroup/all_fingroup.v mathcomp/fingroup/perm.v mathcomp/fingroup/action.v mathcomp/fingroup/fingroup.v mathcomp/fingroup/morphism.v mathcomp/fingroup/presentation.v mathcomp/solvable/gfunctor.v mathcomp/solvable/primitive_action.v mathcomp/solvable/pgroup.v mathcomp/solvable/nilpotent.v mathcomp/solvable/burnside_app.v mathcomp/solvable/gseries.v mathcomp/solvable/extremal.v mathcomp/solvable/center.v mathcomp/solvable/finmodule.v mathcomp/solvable/all_solvable.v mathcomp/solvable/sylow.v mathcomp/solvable/extraspecial.v mathcomp/solvable/alt.v mathcomp/solvable/hall.v mathcomp/solvable/cyclic.v mathcomp/solvable/jordanholder.v mathcomp/solvable/maximal.v mathcomp/solvable/abelian.v mathcomp/solvable/frobenius.v mathcomp/solvable/commutator.v mathcomp/algebra/fraction.v mathcomp/algebra/poly.v mathcomp/algebra/all_algebra.v mathcomp/algebra/mxpoly.v mathcomp/algebra/mxalgebra.v mathcomp/algebra/vector.v mathcomp/algebra/ssrint.v mathcomp/algebra/polydiv.v mathcomp/algebra/ssrnum.v mathcomp/algebra/finalg.v mathcomp/algebra/polyXY.v mathcomp/algebra/intdiv.v mathcomp/algebra/matrix.v mathcomp/algebra/ssralg.v mathcomp/algebra/zmodp.v mathcomp/algebra/ring_quotient.v mathcomp/algebra/interval.v mathcomp/algebra/countalg.v mathcomp/algebra/rat.v mathcomp/field/falgebra.v mathcomp/field/algebraics_fundamentals.v mathcomp/field/fieldext.v mathcomp/field/algnum.v mathcomp/field/finfield.v mathcomp/field/cyclotomic.v mathcomp/field/closed_field.v mathcomp/field/algC.v mathcomp/field/all_field.v mathcomp/field/galois.v mathcomp/field/separable.v > /dev/null
